services:
  bim-clinics:
    build: .
    container_name: bim-clinics
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # DOMAIN PUBLIC
      - "traefik.http.routers.bim-clinics-public.rule=Host(`clinics.bimoporto.my.id`)"
      - "traefik.http.routers.bim-clinics-public.entrypoints=websecure"
      - "traefik.http.routers.bim-clinics-public.tls=true"
      - "traefik.http.routers.bim-clinics-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bim-clinics-public.service=bim-clinics-service"

      # DOMAIN STAFF
      - "traefik.http.routers.bim-clinics-staff.rule=Host(`staff.clinics.bimoporto.my.id`)"
      - "traefik.http.routers.bim-clinics-staff.entrypoints=websecure"
      - "traefik.http.routers.bim-clinics-staff.tls=true"
      - "traefik.http.routers.bim-clinics-staff.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bim-clinics-staff.service=bim-clinics-service"

      # Keduanya menuju container yang sama
      - "traefik.http.services.bim-clinics-service.loadbalancer.server.port=3000"

    networks:
      - coolify

networks:
  coolify:
    external: true