import { useEffect, useState } from 'react';
import { api } from '../lib/api';

type Doc={id:number;document_no:string;patient_name:string;doctor_name:string;registration_no:string;visit_date:string;document_type:string;title:string;content:string;diagnosis?:string|null;created_at:string;rest_start_date?:string;rest_end_date?:string};
type PrintDoc=Doc&{specialization?:string;sip_number?:string;branch_name?:string;branch_address?:string;branch_phone?:string;verification_url:string;qr_data_url:string};
const fmt=(d?:string)=>d?new Date(d).toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'}):'-';
const esc=(v?:string)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));

export default function Admin(){
 const [docs,setDocs]=useState<Doc[]>([]),[msg,setMsg]=useState('');
 const load=()=>api<Doc[]>('/admin/documents?status=WAITING_ADMIN').then(setDocs).catch(e=>setMsg(e.message));
 useEffect(() => { void load(); }, []);
 async function process(id:number,status:'PROCESSED'|'PRINTED'){try{await api(`/admin/documents/${id}/process`,{method:'POST',body:JSON.stringify({status})});setMsg(status==='PRINTED'?'Surat disahkan sebagai sudah dicetak. QR sekarang dapat diverifikasi.':'Surat sudah diproses dan QR dapat diverifikasi.');load();}catch(e){setMsg(e instanceof Error?e.message:'Gagal');}}
 async function printLetter(id:number){
   const w=window.open('','_blank'); if(!w){setMsg('Popup diblokir browser. Izinkan popup untuk mencetak surat.');return;}
   w.document.write('<p style="font-family:sans-serif;padding:30px">Menyiapkan surat BIM CLINICS...</p>');
   try{
     await api(`/admin/documents/${id}/process`,{method:'POST',body:JSON.stringify({status:'PROCESSED'})});
     const d=await api<PrintDoc>(`/admin/documents/${id}/print-data`);
     w.document.open();
     w.document.write(`<!doctype html><html><head><title>${esc(d.document_no)}</title><style>body{font-family:Arial,sans-serif;color:#111;margin:0}.page{width:190mm;min-height:270mm;margin:auto;padding:18mm;box-sizing:border-box}.head{display:flex;justify-content:space-between;border-bottom:3px solid #173d32;padding-bottom:14px}.brand h1{margin:0;font-size:26px}.brand p{margin:4px 0;color:#555}.meta{margin:28px 0 20px}.meta div{display:grid;grid-template-columns:155px 1fr;margin:7px 0}.title{text-align:center;text-decoration:underline;margin:28px 0 20px}.diagnosis{margin:18px 0;padding:12px 14px;border:1px solid #ccd8d4;background:#f7faf9}.diagnosis small{display:block;color:#53665f;margin-bottom:5px}.diagnosis b{font-size:15px}.content{white-space:pre-wrap;line-height:1.7;min-height:160px}.rest{margin:20px 0;padding:12px;border:1px solid #ccc}.foot{display:grid;grid-template-columns:1fr 160px;gap:30px;margin-top:42px;align-items:end}.doctor{text-align:center}.qr{text-align:center;font-size:11px}.qr img{width:125px;height:125px}.qr p{margin:3px 0}.verify-url{font-size:8px;word-break:break-all;color:#666}@media print{.page{margin:0;padding:12mm}}</style></head><body><div class="page"><div class="head"><div class="brand"><h1>BIM CLINICS</h1><p>${esc(d.branch_name||'Klinik')}</p><p>${esc(d.branch_address||'')} ${d.branch_phone?`· ${esc(d.branch_phone)}`:''}</p></div><div><b>${esc(d.document_no)}</b></div></div><h2 class="title">${esc(d.title)}</h2><div class="meta"><div><span>Nama Pasien</span><b>: ${esc(d.patient_name)}</b></div><div><span>Tanggal Berobat</span><b>: ${fmt(d.visit_date)}</b></div><div><span>No. Registrasi</span><b>: ${esc(d.registration_no)}</b></div></div>${d.diagnosis?`<div class="diagnosis"><small>Diagnosis</small><b>${esc(d.diagnosis)}</b></div>`:''}<div class="content">${esc(d.content)}</div>${d.rest_start_date||d.rest_end_date?`<div class="rest"><b>Rekomendasi istirahat:</b> ${fmt(d.rest_start_date)} sampai ${fmt(d.rest_end_date)}</div>`:''}<div class="foot"><div class="doctor"><p>Dokter Pemeriksa,</p><br/><br/><b>${esc(d.doctor_name)}</b><p>${esc(d.specialization||'')}</p><p>SIP: ${esc(d.sip_number||'-')}</p></div><div class="qr"><img src="${d.qr_data_url}"/><b>SCAN UNTUK VERIFIKASI</b><p>BIM CLINICS</p><div class="verify-url">${esc(d.verification_url)}</div></div></div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);
     w.document.close();load();
   }catch(e){w.close();setMsg(e instanceof Error?e.message:'Gagal menyiapkan surat');}
 }
 return <><header className="page-head"><div><small>BIM CLINICS · ADMINISTRATION</small><h1>Surat dari Dokter</h1><p>Setiap surat memiliki nomor unik dan QR untuk verifikasi kunjungan pasien.</p></div></header>{msg&&<div className="alert">{msg}</div>}<section className="panel"><div className="panel-title"><h2>Menunggu diproses</h2></div>{docs.length===0?<div className="empty">Tidak ada surat menunggu.</div>:docs.map(d=><article className="document-card" key={d.id}><div className="document-head"><div><b>{d.title}</b><small>{d.document_no} · {d.patient_name} · {d.registration_no}</small></div><span className="pill">{d.document_type}</span></div>{d.diagnosis&&<div className="document-diagnosis"><small>Diagnosis</small><b>{d.diagnosis}</b></div>}<p>{d.content}</p><small>Berobat {fmt(d.visit_date)} · Dokter {d.doctor_name}</small><div className="actions"><button className="secondary" onClick={()=>process(d.id,'PROCESSED')}>Sahkan surat</button><button className="primary" onClick={()=>printLetter(d.id)}>Cetak + QR</button><button className="ghost" onClick={()=>process(d.id,'PRINTED')}>Tandai dicetak</button></div></article>)}</section></>
}
